version: "3.3"
services:
  db:
    image: mysql:8
    container_name: mutbly_db
    ports:
      - "63306:3306"
    environment:
      MYSQL_DATABASE: "mutbly_db"
      MYSQL_USER: "mutbly_user"
      MYSQL_PASSWORD: "mutbly_password"
      MYSQL_ROOT_PASSWORD: "rootpass"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci